In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("2025-10-02T1309_Grades-PHYS_201.csv")
df.head()

,Student,ID,SIS User ID,SIS Login ID,Section,Chapter 1 Prelecture Video 1 (1859100),Chapter 1 Prelecture Video 2 (1859101),Chapter 2 Prelecture Video 1 (1859104),Chapter 2 Prelecture Video 2 (1859105),Chapter 2 Prelecture Video 3 (1859106),...,Exam 2 Final Score,Exam 2 Unposted Final Score,Final Exam Current Score,Final Exam Unposted Current Score,Final Exam Final Score,Final Exam Unposted Final Score,Current Score,Unposted Current Score,Final Score,Unposted Final Score
0,NaN,NaN,NaN,NaN,NaN,Manual Posting,Manual Posting,Manual Posting,Manual Posting,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Points Possible,NaN,NaN,NaN,NaN,10.00,10.00,10.00,10.00,10.0,...,(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only)
2,"Acuna, Alana",154045.0,951950659.0,aacuna,"PHYS 201 (CRN 14367), PHYS 201 (CRN 14370), an...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Autar, Akash",140426.0,951875528.0,aautar,"PHYS 201 (CRN 14367), PHYS 201 (CRN 14370), an...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Barnes, Aj",190949.0,952105847.0,ajbarnes,"PHYS 201 (CRN 14367), PHYS 201 (CRN 14370), an...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df['Student'][2:-1].to_list()

['Acuna, Alana',
 'Autar, Akash',
 'Barnes, Aj',
 'Bertelsen, Hailey',
 'Bradshaw, Charlie',
 'Cook Diaz, Rowan',
 'Cooper, Mikala',
 'Corcoran, Nick',
 'Craddock, Yun',
 'De Leon, Isaiah',
 'Dennis, Kelsey',
 'Ellorin, Ysabella',
 'Enright, Taylor',
 'Finemel, Annie',
 'Freed, Drake',
 'Friel, Liem',
 'Fulk, Logan',
 'Gomez-Chan, Fabiola',
 'Hacker, Connor',
 'Hansen, Reese',
 'Hines, Nadia',
 'Hussein, Rima',
 'Kendall, Ava',
 'Khanna, Ananya',
 'Krueger, Tessa',
 'Lage, Adeline',
 'Lambo, Dexter',
 'Lara, Diego',
 'Lara, Victor',
 'Leach, Gwendolynn',
 'Lebo, Rachel',
 'Lilly, Genevieve',
 'Lucas, Grae',
 'Maher, Kyle',
 'Martin, Lea',
 'Martinez, Marina',
 "McDonald, Cam'Ron",
 'Mehta, Jhil',
 'Mosolgo, Anabella',
 'Narbaez, Adrien',
 'Nollette, Isabelle',
 'Owens, Richie',
 'Palmer, B J',
 'Partain, Adrian',
 'Petitt, McKenzie',
 'Printz, Dane',
 'Quizon, Ivanna',
 'Rathore, Max',
 'Roan, Dana',
 'Robin, Aidan',
 'Rook, Cassidy',
 'Roscher, Wyatt',
 'Rueter, Rochelle',
 'Rutan, Triston',
 'Sanada, Maia',
 'Schmidt, Thomas',
 'Schmitt, Eliot',
 'Shaft, Isabella',
 'Shepler, Izzy',
 'Silvia, Noah',
 'Spengler, Sascha',
 'Tarbox, Michael',
 'Toyooka, Luke',
 'Uehara, Kierstin',
 'Valdez, Bella',
 'Walts, Benjamin',
 'Watson, Magdalyn',
 'Wenz, Kamryn',
 'Winchester, Sierra',
 'Wright, Jace']

In [3]:
import qrcode
from qrcode.constants import ERROR_CORRECT_M

def make_qr(url: str, outfile: str = "qr.png"):
    qr = qrcode.QRCode(
        version=None,                 # automatic size
        error_correction=ERROR_CORRECT_M,  # 15% restoration
        box_size=10,                  # pixel size of each “box”
        border=4                      # quiet zone (boxes)
    )
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    img.save(outfile)
    print(f"Saved {outfile}")

make_qr("https://dlai211.github.io/sign-in/index.html", "website_qr.png")

Saved website_qr.png

In [1]:
!pip install qrcode

Defaulting to user installation because normal site-packages is not writeable
Collecting qrcode
  Obtaining dependency information for qrcode from https://files.pythonhosted.org/packages/dd/b8/d2d6d731733f51684bbf76bf34dab3b70a9148e8f2cef2bb544fccec681a/qrcode-8.2-py3-none-any.whl.metadata
  Downloading qrcode-8.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from qrcode) (0.4.6)
Downloading qrcode-8.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/46.0 kB ? eta -:--:--
   ---------------------------------------- 46.0/46.0 kB ? eta 0:00:00
Installing collected packages: qrcode
Successfully installed qrcode-8.2

  WARNING: The script qr.exe is installed in 'C:\Users\laiji\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.